spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:mariadb://localhost:33306/modeKasu?useUnicode=yes&characterEncoding=UTF-8&rewriteBatchedStatements=true
    driver-class-name: org.mariadb.jdbc.Driver
    maximum-pool-size: 10
    max-lifetime: 30000
    connection-timeout: 3000
    username: modeKasu
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
#  data:
#    redis:
#      host: localhost
#      port: 6380
#  cache:
#    type: redis

  thymeleaf:
    cache=false:

springdoc :
  override-with-generic-response : false

toss:
  client:
    key: ${TOSS_CLIENT_KEY}
  secret:
    key: ${TOSS_SECRET_KEY}
  security:
    key: ${TOSS_SECURITY_KEY}
---
spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:h2:mem:test;MODE=MySQL;DATABASE_TO_LOWER=TRUE;INIT=CREATE SCHEMA IF NOT EXISTS coupon;
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
#  data:
#    redis:
#      host: localhost
#      port: 6380

toss:
  client:
    key: ${TOSS_CLIENT_KEY}
  secret:
    key: ${TOSS_SECRET_KEY}
  security:
    key: ${TOSS_SECURITY_KEY}
---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:mariadb://${PROD_DB_URL}:${PROD_DB_PORT}/${PROD_DB_DATA_BASE}?useUnicode=yes&characterEncoding=UTF-8&rewriteBatchedStatements=true
    driver-class-name: org.mariadb.jdbc.Driver
    maximum-pool-size: 10
    max-lifetime: 30000
    connection-timeout: 3000
    username: ${PROD_DB_USER_NAME}
    password: ${PROD_DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

#  data:
#    redis:
#      host: PROD_URL
#      port: 6380

springdoc :
  override-with-generic-response : false

toss:
  client:
    key: ${TOSS_CLIENT_KEY}
  secret:
    key: ${TOSS_SECRET_KEY}
  security:
    key: ${TOSS_SECURITY_KEY}